name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make LDFLAGS="-s -static" CFLAGS="-O2 -Werror"

